const mongoose = require('mongoose');
const Schema = mongoose.Schema;

module.exports = mongoose.model('Citizen', new Schema({
    srno: String,
    villageId: String,
    name: String,
    wife_name: String,
    mobile_no: String,
    address: String,
    malmatta: [{
        malmatta_number: String,
        malmatta_type: String,
        formula: String,
        area: String,
        majla_tal_use: String,
        majla_tal_year: String,
        majla_tal_area: String,
        majla_first_use: String,
        majla_first_year: String,
        majla_first_area: String,
        majla_second_use: String,
        majla_second_year: String,
        majla_second_area: String,
        manora_khulla_area: String,
        manora_talghar_area: String,
        land_type: String,
        ward_name: String,
        payee_name: String,
        home_number: String,
        survey_number: String,
        previous_gharpatti: String,
        previous_veej: String,
        previous_aarogya: String,
        previous_panipatti: String,
        east: String,
        west: String,
        south: String,
        north: String,
        door: String,
        panipatti_kar_type: String,
        bhandwali_mulya: String,
        current_gharpatti: String,
        current_veej: {type: String, default: 0},
        current_aarogya: {type: String, default: 0},
        current_panipatti: {type: String, default: 0},
        total: Number,
        paid_gharpatti: String,
        paid_veej: String,
        paid_aarogya: String,
        paid_panipatti: String,
        bharank_rate: String,
        ready_reknar: String,
        kar_rate: String,
        ghasara_dar: String,
        previous_paid_gharpatti: {type: String, default: 0},
        previous_paid_panipatti: {type: String, default: 0},
        previous_paid_veej: {type: String, default: 0},
        previous_paid_aarogya: {type: String, default: 0},
        current_paid_gharpatti: {type: String, default: 0},
        current_paid_panipatti: {type: String, default: 0},
        current_paid_veej: {type: String, default: 0},
        current_paid_aarogya: {type: String, default: 0}
    }]
}))