const mongoose = require('mongoose');
const Schema = mongoose.Schema;

module.exports = mongoose.model('Citizen', new Schema({
    villageId: String,
    name: String,
    wife_name: String,
    mobile_no: String,
    address: String,
    malmatta_number: String,
    malmatta_type: String,
    formula: String,
    area: String,
    majla_tal_use: String,
    majla_tal_year: String,
    majla_tal_area: String,
    majla_tal_type: String,
    majla_first_use: String,
    majla_first_year: String,
    majla_first_area: String,
    majla_first_type: String,
    majla_second_use: String,
    majla_second_year: String,
    majla_second_area: String,
    majla_second_type: String,
    land_type: String,
    ward_name: String,
    payee_name: String,
    home_number: String,
    survey_number: String,
    previous_gharpatti: String,
    previous_veej: String,
    previous_aarogya: String,
    previous_panipatti: String,
    east: String,
    west: String,
    south: String,
    north: String,
    door: String,
    panipatti_kar_type: String
}))